openapi: 3.1.0
info:
  title: Recruitments
  description: Recruitments
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/v1/'
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
paths:
  /recruitments:
    post:
      security:
        - cookieAuth: [ ]
      summary: Register Recruitment
      description: |
        Register Recruitment
      requestBody:
        description: Register Recruitment
        content:
          application/json:
            schema:
              type: object
              properties:
                positions:
                  type: array
                  items:
                    type: string
                  example: [ "frontend", "backend" ]
                skills:
                  type: array
                  items:
                    type: string
                  example: [ "go", "java" ]
                proceed:
                  type: string
                  example: "ONLINE"
                  description: |
                    "ALL", "ONLINE", "OFFLINE"
                category:
                  type: string
                  example: "STUDY"
                  description: |
                    "STUDY", "PROJECT"
                contact:
                  type: string
                  example: support@topu.jp
                deadline:
                  type: string
                  example: 2025-02-22
                period:
                  type: number
                  example: 3
                  description:
                    1,2,3,4,5,6,12 （何ヶ月かを意味する）
                members:
                  type: number
                  example: 2
                  description: |
                    何名募集しているかを意味する
                title:
                  type: string
                  example: "CleanCode読書会"
                content:
                  type: string
                  example: "CleanCodeの信者になりたい方大歓迎です。"
              required:
                - positions
                - skills
                - proceed
                - category
                - contact
                - deadline
                - period
                - members
                - title
                - content
      responses:
        "201":
          description: Recruitment Create Success
    get:
      security:
        - cookieAuth: [ ]
      summary: Get All
      description: |
        Get All Recruitments  
        -> `/recruitments?keyword=勉強会&skills=go,java&position=backend&page=1&limit=12`
      parameters:
        - name: keyword
          in: query
          description: Search keyword
          schema:
            type: string
            format: string
        - name: skills
          in: query
          description: Search criteria for skills
          schema:
            format: string
            type: string
        - name: positions
          in: query
          description: Search criteria for positions
          schema:
            format: string
            type: string
        - name: page
          in: query
          description: Search criteria for page number
          schema:
            format: string
            type: string
        - name: limit
          in: query
          description: Search criteria for display size
          schema:
            format: string
            type: string
      responses:
        "200":
          description: Get Recruitment
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                      example: 1
                    positions:
                      type: array
                      items:
                        type: string
                      example: [ "frontend", "backend" ]
                    skills:
                      type: array
                      items:
                        type: string
                      example: [ "go", "java" ]
                    proceed:
                      type: string
                      example: "online"
                      description: |
                        proceed には "online", "offline", "all" が存在する
                    category:
                      type: string
                      example: "study"
                      description: |
                        category には "study", "project" が存在する
                    contact:
                      type: string
                      example: "test@topu.co.jp"
                    deadline:
                      type: string
                      example: "2025-02-05"
                    period:
                      type: integer
                      example: 3
                      description: 進行期間
                    members:
                      type: integer
                      example: 2
                      description: 募集人数
                    title:
                      type: string
                      example: "すごい勉強会"
                    content:
                      type: string
                      example: "一緒にやりましょう！"
  /recruitments/{id}:
    put:
      security:
        - cookieAuth: [ ]
      summary: Update Recruitment By ID
      description: |
        Register Recruitment
      parameters:
        - name: id
          in: path
          description: Recruitment ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update Recruitment By ID
        content:
          application/json:
            schema:
              type: object
              properties:
                positions:
                  type: array
                  items:
                    type: string
                  example: [ "frontend", "backend" ]
                skills:
                  type: array
                  items:
                    type: string
                  example: [ "go", "java" ]
                proceed:
                  type: string
                  example: "ONLINE"
                  description: |
                    "ALL", "ONLINE", "OFFLINE"
                category:
                  type: string
                  example: "STUDY"
                  description: |
                    "STUDY", "PROJECT"
                contact:
                  type: string
                  example: "support@topu.jp"
                deadline:
                  type: string
                  example: "2025-02-22"
                period:
                  type: number
                  example: 3
                  description:
                    1,2,3,4,5,6,12 （何ヶ月かを意味する）
                members:
                  type: number
                  example: 2
                  description: |
                    何名募集しているかを意味する
                title:
                  type: string
                  example: "CleanCode読書会"
                content:
                  type: string
                  example: "CleanCodeの信者になりたい方大歓迎です。"
              required:
                - positions
                - skills
                - proceed
                - category
                - contact
                - deadline
                - period
                - members
                - title
                - content
      responses:
        "200":
          description: Recruitment Create Success
    get:
      security:
        - cookieAuth: [ ]
      summary: Get One
      description: |
        Get Recruitment By ID
      parameters:
        - name: id
          in: path
          description: Recruitment ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Get Recruitment
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    example: 1
                  positions:
                    type: array
                    items:
                      type: string
                    example: [ "frontend", "backend" ]
                  skills:
                    type: array
                    items:
                      type: string
                    example: [ "go", "java" ]
                  proceed:
                    type: string
                    example: "online"
                    description: |
                      proceed には "online", "offline", "all" が存在する
                  category:
                    type: string
                    example: "study"
                    description: |
                      category には "study", "project" が存在する
                  contact:
                    type: string
                    example: "test@topu.co.jp"
                  deadline:
                    type: string
                    example: "2025-02-05"
                  period:
                    type: integer
                    example: 3
                    description: 進行期間
                  members:
                    type: integer
                    example: 2
                    description: 募集人数
                  title:
                    type: string
                    example: "すごい勉強会"
                  content:
                    type: string
                    example: "一緒にやりましょう！"
    delete:
      security:
        - cookieAuth: [ ]
      summary: Delete
      description: |
        Delete Recruitment By ID
      parameters:
        - name: id
          in: path
          description: Recruitment ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Delete Recruitment