// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PositionsColumns holds the columns for the "positions" table.
	PositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// PositionsTable holds the schema information for the "positions" table.
	PositionsTable = &schema.Table{
		Name:       "positions",
		Columns:    PositionsColumns,
		PrimaryKey: []*schema.Column{PositionsColumns[0]},
	}
	// RecruitmentsColumns holds the columns for the "recruitments" table.
	RecruitmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "proceed", Type: field.TypeString},
		{Name: "category", Type: field.TypeString},
		{Name: "contact", Type: field.TypeString},
		{Name: "dead_line", Type: field.TypeTime},
		{Name: "period", Type: field.TypeInt8},
		{Name: "members", Type: field.TypeInt8},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "users_id", Type: field.TypeInt, Nullable: true},
	}
	// RecruitmentsTable holds the schema information for the "recruitments" table.
	RecruitmentsTable = &schema.Table{
		Name:       "recruitments",
		Columns:    RecruitmentsColumns,
		PrimaryKey: []*schema.Column{RecruitmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recruitments_users_recruitments",
				Columns:    []*schema.Column{RecruitmentsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
	}
	// TransientUsersColumns holds the columns for the "transient_users" table.
	TransientUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sub", Type: field.TypeString, Unique: true},
	}
	// TransientUsersTable holds the schema information for the "transient_users" table.
	TransientUsersTable = &schema.Table{
		Name:       "transient_users",
		Columns:    TransientUsersColumns,
		PrimaryKey: []*schema.Column{TransientUsersColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sub", Type: field.TypeString, Unique: true},
		{Name: "nickname", Type: field.TypeString, Unique: true},
		{Name: "career_year", Type: field.TypeInt8},
		{Name: "profile_url", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// RecruitmentSkillsColumns holds the columns for the "recruitment_skills" table.
	RecruitmentSkillsColumns = []*schema.Column{
		{Name: "recruitment_id", Type: field.TypeInt},
		{Name: "skill_id", Type: field.TypeInt},
	}
	// RecruitmentSkillsTable holds the schema information for the "recruitment_skills" table.
	RecruitmentSkillsTable = &schema.Table{
		Name:       "recruitment_skills",
		Columns:    RecruitmentSkillsColumns,
		PrimaryKey: []*schema.Column{RecruitmentSkillsColumns[0], RecruitmentSkillsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recruitment_skills_recruitment_id",
				Columns:    []*schema.Column{RecruitmentSkillsColumns[0]},
				RefColumns: []*schema.Column{RecruitmentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "recruitment_skills_skill_id",
				Columns:    []*schema.Column{RecruitmentSkillsColumns[1]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RecruitmentPositionsColumns holds the columns for the "recruitment_positions" table.
	RecruitmentPositionsColumns = []*schema.Column{
		{Name: "recruitment_id", Type: field.TypeInt},
		{Name: "position_id", Type: field.TypeInt},
	}
	// RecruitmentPositionsTable holds the schema information for the "recruitment_positions" table.
	RecruitmentPositionsTable = &schema.Table{
		Name:       "recruitment_positions",
		Columns:    RecruitmentPositionsColumns,
		PrimaryKey: []*schema.Column{RecruitmentPositionsColumns[0], RecruitmentPositionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recruitment_positions_recruitment_id",
				Columns:    []*schema.Column{RecruitmentPositionsColumns[0]},
				RefColumns: []*schema.Column{RecruitmentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "recruitment_positions_position_id",
				Columns:    []*schema.Column{RecruitmentPositionsColumns[1]},
				RefColumns: []*schema.Column{PositionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserPositionColumns holds the columns for the "user_position" table.
	UserPositionColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "position_id", Type: field.TypeInt},
	}
	// UserPositionTable holds the schema information for the "user_position" table.
	UserPositionTable = &schema.Table{
		Name:       "user_position",
		Columns:    UserPositionColumns,
		PrimaryKey: []*schema.Column{UserPositionColumns[0], UserPositionColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_position_user_id",
				Columns:    []*schema.Column{UserPositionColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_position_position_id",
				Columns:    []*schema.Column{UserPositionColumns[1]},
				RefColumns: []*schema.Column{PositionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserSkillsColumns holds the columns for the "user_skills" table.
	UserSkillsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "skill_id", Type: field.TypeInt},
	}
	// UserSkillsTable holds the schema information for the "user_skills" table.
	UserSkillsTable = &schema.Table{
		Name:       "user_skills",
		Columns:    UserSkillsColumns,
		PrimaryKey: []*schema.Column{UserSkillsColumns[0], UserSkillsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_skills_user_id",
				Columns:    []*schema.Column{UserSkillsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_skills_skill_id",
				Columns:    []*schema.Column{UserSkillsColumns[1]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PositionsTable,
		RecruitmentsTable,
		SkillsTable,
		TransientUsersTable,
		UsersTable,
		RecruitmentSkillsTable,
		RecruitmentPositionsTable,
		UserPositionTable,
		UserSkillsTable,
	}
)

func init() {
	RecruitmentsTable.ForeignKeys[0].RefTable = UsersTable
	RecruitmentSkillsTable.ForeignKeys[0].RefTable = RecruitmentsTable
	RecruitmentSkillsTable.ForeignKeys[1].RefTable = SkillsTable
	RecruitmentPositionsTable.ForeignKeys[0].RefTable = RecruitmentsTable
	RecruitmentPositionsTable.ForeignKeys[1].RefTable = PositionsTable
	UserPositionTable.ForeignKeys[0].RefTable = UsersTable
	UserPositionTable.ForeignKeys[1].RefTable = PositionsTable
	UserSkillsTable.ForeignKeys[0].RefTable = UsersTable
	UserSkillsTable.ForeignKeys[1].RefTable = SkillsTable
}
