name: topu

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [ submitted ]

permissions:
  id-token: write
  contents: read
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set secrets
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}  # GitHub Secrets에서 가져온 값 설정
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          JWT_SIGN_KEY: ${{ secrets.JWT_SIGN_KEY }}
        run: |
          # application-local.properties 파일에 client_id를 설정
          echo "spring.security.oauth2.client.registration.google.client-id=$CLIENT_ID" >> src/main/resources/application-local.properties
          echo "spring.security.oauth2.client.registration.google.client-secret=$CLIENT_SECRET" >> src/main/resources/application-local.properties
          echo "jwt.sign.key=$JWT_SIGN_KEY" >> src/main/resources/application-local.properties          

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/docs/asciidoc

  deploy-docs:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Package

      - name: List files in build/libs (debugging)
        run: ls -la .

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        id: deployment